# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: ''
    url: /
    weight: 5
  # - name: Topics
  #   url: tags/
  #   weight: 20
  # - name: Uses
  #   url: uses/
  #   weight: 30
